### ISSUE TITLE
hasCoaching

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#1]
> Source: [GoodGym](http://data.goodgym.org/), [Open Sessions](http://data.opensessions.io/)

Boolean representing whether or not a session is coached. Note that the coach name is not always specified, and this is different to having a "leader", as the leader may or may not be a coach.

Example:
```
"hasCoaching": false
```

**Comment by ldodds** [comment]
There's now a new property `isCoached` in the main namespace and modelling spec. https://www.openactive.io/ns/#isCoached

Suggest any apps using an experimental property switch over to using that.
