### ISSUE TITLE
Place::meetingPoint

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#10]
> Property: meetingPoint
> Source: [GoodGym](http://data.goodgym.org/), [Open Sessions](http://data.opensessions.io/), [Our Parks](http://data.ourparks.org.uk/), [British Cycling](https://github.com/openactive/activation/issues/5)
> Domain: Place

A brief description of where to meet - especially useful for outdoor activities where the postcode and address is not sufficient. 

Examples:
- `"Be careful – this is different to 289 Cambridge Heath Road. The Arch gallery is 200m south of Cambridge Heath Road rail station, and north of Bethnal Green tube. The Arch Gallery is hard to spot, look out for the zebra crossing right outside the door."` (GoodGym)
- `"Ongoing work at the Totenham FC means access to the pool are from the Northumberland Park road end of worchester avenue side entrance of the school. Access is signposted inside of building with on site staff in case of emergencies"` (Open Sessions)
- `"Basketball Courts"` (Our Parks)
- `"Outside City of London building with Public Toilets Parliament Hill Fields / Highgate Road"` (British Cycling)

**Comment by nickevansuk** [comment]
This could be covered by the "description" property of `Place`

**Comment by nickevansuk** [comment]
Although on reflection, the description is likely to be reserved for a description of the venue itself, rather than specific instructions on how to find it.

**Comment by ldodds** [comment]
We discussed this use case on the last call. There's a property defined in the editors draft already:

https://www.openactive.io/ns/#attendeeInstructions

"Provides additional notes and instructions for event attendees. E.g. more information on how to find the event, what to bring, etc."

No need for another descriptive property.

**Comment by nickevansuk** [comment]
This seems to be serving a slightly more broad purpose... Open Sessions and GoodGym both have specific meeting point info

**Comment by ldodds** [comment]
New meetingPoint property added to the modelling specification and namespace (https://www.openactive.io/ns/#meetingPoint).
