### ISSUE TITLE
ageRange for Offers

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#11]
> Source: [Fusion](http://data.fusion-lifestyle.com), [Better](http://data.better.org.uk/)

For offers that are for a particular age group (e.g. "Junior non-member"), include an age range to which this applies.

For example:

```
  "offer": [
    {
      "name": "Senior non-member",
      "price": "6.60",
      "priceCurrency": "GBP",
      "ageRange":"60",
      "type": "Offer"
    },
    {
      "name": "Adult non-member",
      "price": "6.60",
      "priceCurrency": "GBP",
      "ageRange":"16-59",
      "type": "Offer"
    },
    {
      "name": "Junior non-member",
      "price": "6.60",
      "priceCurrency": "GBP",
      "ageRange":"0-15",
      "type": "Offer"
    }
  ]
```

**Comment by ldodds** [comment]
There's no need for a new property here, just defining where ageRange can be used. Will include this in openactive/modelling-opportunity-data/issues/68.

**Comment by nickevansuk** [comment]
This property was included in the [Modelling Opportunity Specification 2.0](https://www.openactive.io/modelling-opportunity-data/2.0), so this issue can now be closed.
