### ISSUE TITLE
urlTemplate

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#14]
> Source: [Bookwhen](http://data.bookwhen.com/)

For events that specify a schedule, where the Offer or Event url applies to each occurrence in the schedule, a urlTemplate allows a user to be linked directly to the relevant page for that occurrence. Value of urlTemplate should be of type http://schema.org/urlTemplate.

Example use:

```
"beta:urlTemplate": "https://bookwhen.com/bounce/e/ev-sird?startDate={startDate}"
```

**Comment by jopotts** [comment]
Recurring event schedules now have a template url like this (slightly different from your example):

```
https://bookwhen.com/hulafit/e/ev-s51e-{YYYYMMDDHHMISS}?r=oa
```

_btw The end param is so we can mark new customers as sourced from OA to extol its virtue._

**Comment by nickevansuk** [comment]
Awesome @jopotts!

It's interesting to think about how we allow for date formatting and child properties in a template like this that still supports multiple fields: e.g. could we do:

`https://bookwhen.com/hulafit/e/ev-{subEvent.id}-{startdate:YYYYMMDDHHMISS}?r=oa`

Perhaps something else for this discussion when we have a few more folks implementing this property and bringing their use cases into the mix. Love how simple this is though!

**Comment by ldodds** [comment]
Note this is now covered by this proposal: https://github.com/openactive/modelling-opportunity-data/issues/72. It provides 2 properties to support both `id` and `url` and includes some extra flexibility.

btw, it looks to me like the bookwhen `eventSchedule`s don't conform to the latest Schema.org definitions. See the accepted pull request here: https://github.com/schemaorg/schemaorg/pull/1693.

**Comment by nickevansuk** [comment]
This property was included in the [Modelling Opportunity Specification 2.0](https://www.openactive.io/modelling-opportunity-data/2.0), so this issue can now be closed.
