### ISSUE TITLE
equipment

### ISSUE THREAD

**Issue by philjackson** [openactive/ns-beta#16]
> Source: EMD
> Context: Event

A Text property that allows an organiser to specify equipment requirements/recommendations for an event.

    { "equipment": "Tennis racket, tennis balls" }

**Comment by ldodds** [comment]
Both #15 and #16 are currently covered by the `oa:attendeeInstructions` property, which is defined as:

```Provides additional notes and instructions for event attendees. This information is targetted at attendees rather than potential participants. The instructions might include information on what to bring, what to wear, how to find the event, etc.```

https://www.openactive.io/ns/#attendeeInstructions

A publisher that currently has separate clothing and equipment properties could publish those by combining them into a single property.

I think we need to highlight the data consumer use case that supports addition of these two new properties. As they are unstructured text, then they can't be used for filtering. 

Will consumers always want to be able to split these out into separate properties, or can they be handled by the existing property for now?

**Comment by philjackson** [comment]
Closing #15 and #16 as `oa:attendeeInstructions` has proven adequate.
