### ISSUE TITLE
parking

### ISSUE THREAD

**Issue by philjackson** [openactive/ns-beta#17]
> Source: EMD, British Cycling
> Context: Event

A property that details parking suitability. Placed on Event as this field could be used to detail parking options not directly at the location of the event.

    {
      "parking": {
        "type": "ParkingFacility",
        "description": "Free carpark belonging to the Sports centre.",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "Kentish Town Sports Centre",
          "addressLocality": "Camden",
          "addressRegion": "London West",
          "postalCode": "NW5 3DU"
        }
      }
    }

**Comment by nickevansuk** [comment]
This has been suggested as an **amenityFeature** with value as follows:

```
            {
              "name":"Parking",
              "value":true,
              "description": "Pay & Display Near Start Point",
              "type":"Parking"
            }
```

**Comment by ldodds** [comment]
Yes, this is covered by openactive/modelling-opportunity-data/issues/70 no need for a beta property for testing this.
