### ISSUE TITLE
offer

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#4]
> Source:  [GO Mammoth](http://data.gomammoth.co.uk/), [Better](http://data.better.org.uk/), [Fusion](http://data.fusion-lifestyle.com), [activeNewham](http://data.activenewham.org.uk/)

Useful to have the price, name, and URL of specific offers (this is just pulled from schema.org)

**Comment by ldodds** [comment]
Closing as covered by schema.org.

If there's a usage pattern to document then best to file an issue, or a PR for the primer

**Comment by nickevansuk** [comment]
Perfect, have filed here https://github.com/openactive/opportunity-data-primer/issues/4
