### ISSUE TITLE
paymentFrequency

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#5]
> Source: [GO Mammoth](http://data.gomammoth.co.uk/), [Better](http://data.better.org.uk/)

For memberships, it is useful to know the frequency associated with the cost within an offer. E.g. "monthly" or "annual". This allows the data consumer to display and filter on memberships accordingly.

**Comment by ldodds** [comment]
This would be an aspect of the Product or Service associated with the Offer. I've not yet delved into how Schema.org recommends use of those terms, but something to explore further in our work on booking.

**Comment by ldodds** [comment]
Am going to close this issue. Based on the reports on GetTheData, neither of these providers are currently testing this property. We can pick up discussion around memberships when we get to that part of booking.
