### ISSUE TITLE
imageCrop

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#7]
> Source:  [GoodGym](http://data.goodgym.org/)

Array of https://schema.org/ImageObject - versions of the main image with different dimensions, useful for situations where photos are manually cropped by users to match. Width and height should be included for each.

**Comment by ldodds** [comment]
As noted in #8 if theres already a schema.org term then we don't have to define a new one here.

**Comment by nickevansuk** [comment]
I believe although schema.org includes ImageObject, it doesn't include a property containing an array of them that satisfies this requirement (different cropped image sizes)? Please do close if I'm mistaken?

**Comment by ldodds** [comment]
Pretty much any schema.org property can be a single value or an array.

So you can specify an array of logos or images.

Images next can have a height and width. You can also indicate if there's a thumbnail.

This early example illustrates the usage

https://github.com/openactive/w3c-cg-example-data/blob/master/examples/good-gym.jsonld

**Comment by nickevansuk** [comment]
Ok perfect 👍

**Comment by nickevansuk** [comment]
I've added an issue in to the primer to clarify this: https://github.com/openactive/opportunity-data-primer/issues/5
