### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#8]
> Source:  [Playwaze](http://data.playwaze.com/)

https://schema.org/logo used within organizer - recommended PNG logo

Helpful for data consumers who want to display a logo for the organiser of the session

**Comment by ldodds** [comment]
If there's already a schema.org property then we dont need to duplicate it in the beta namespace, just use the existing property.

I think the same applies to #7. Any existing schema.org property can be added already. Beta should just be for new custom properties we want to define

**Comment by nickevansuk** [comment]
Excellent, have raised as https://github.com/openactive/opportunity-data-primer/issues/3
