### ISSUE TITLE
availability

### ISSUE THREAD

**Issue by nickevansuk** [openactive/ns-beta#9]
> Source:  [Better](http://data.better.org.uk/), [Fusion](http://data.fusion-lifestyle.com), [activeNewham](http://data.activenewham.org.uk/)

For data publishers not wishing to disclose the granular availability of their sessions openly, this property offers 3 options:
- `"available"` - More than 5 spaces are available
- `"limited"` - 5 spaces or less are available
- `"none"` - 0 spaces are available

**Comment by ldodds** [comment]
Few comments on this:

Firstly, zero availability is already covered by `remainingAttendeeCount` with a value of zero. So its possible to communicate when an event is fully booked, even if a more granular count isn't available in the interim

Secondly, I'm not sure how generally useful those two categories are. The obvious example being a drop-in five a-side game. I'm way about defining fixed bands in the standard. 

Do any of the data publishers who are reluctant to share availability currently expose this information in other ways?

I propose that we defer this to when we look at booking, etc. Another way to handle it as part of a booking API would be a lookup to indicate whether there is still availability for a specific event. That wouldn't disclose numbers.

Alternatively, the banding could be defined as a range, e.g. explicitly include ">n" or "<n" in the data.

**Comment by nickevansuk** [comment]
Allowing this data to be published provides a means for a user to search for available spaces, and limits traffic to a platform to track number of bookings (rather than number of searches).

Totally agree with fixed bands being an issue. To overcome this, should follow your suggestion and iterate this within beta to e.g. "remainingAttendeeCount" with possible values of ">n" and "<n".

A mapping from the existing implementation above would then be:
- `"available"` => `">5"`
- `"limited"` => `"<6"`
- `"none"` - => `0`

**Comment by ldodds** [comment]
We need to revisit this:

* we're specifying fine-grained availability checks for booking, that's using `remainingAttendeeCapacity` too
* there are two other proposals here for [registrationCount](https://github.com/openactive/ns-beta/issues/13) and [attendeeCount](https://github.com/openactive/ns-beta/issues/12) both of which provide ways to share more, rather than less information which could be used to track participation.
* we're moving away (e.g. in ageRange) from properties with micro-syntax to explicit ranges

**Comment by nickevansuk** [comment]
Closing and removing from beta to reflect closure of https://github.com/openactive/modelling-opportunity-data/issues/109
